CREATE DATABASE CLINICA;

USE CLINICA;

CREATE TABLE PROPRIETARIO
(
	COD_PROP INT PRIMARY KEY AUTO_INCREMENT,
    NOM_PROP VARCHAR(100),
    DES_ENDERE_PROP VARCHAR (400),
    NUM_TELEF_PROP CHAR(15)
);

CREATE TABLE VETERINARIO
(
	COD_VETER INT PRIMARY KEY AUTO_INCREMENT,
    NOM_VETER VARCHAR(100),
    DES_ESPEC_VETER VARCHAR(40)
);

CREATE TABLE ANIMAL
(
	COD_ANIMAL INT PRIMARY KEY AUTO_INCREMENT,
    COD_PROP INT,
    COD_VETER INT,
    FOREIGN KEY (COD_PROP) REFERENCES PROPRIETARIO (COD_PROP),
	FOREIGN KEY (COD_VETER) REFERENCES VETERINARIO (COD_VETER),
    NOM_ANIMAL VARCHAR (100),
    DAT_NASC_ANIMAL DATE,
    DES_RACA_ANIMAL VARCHAR(20),
    DES_SEXO_ANIMAL CHAR(1)
);

INSERT INTO PROPRIETARIO (NOM_PROP, DES_ENDERE_PROP, NUM_TELEF_PROP)
VALUES
("Bruna Hamada", "Av. Paulista, 1200", "(11)98866-9988"),
("Luiza Gaza", "Av. Brasil, 350", "(21)3456-8634"),
("Martim Carlos","Al. Santos, 126","(11)98789-9988"),
("Rafael Falcão","Av. Ibirapuera, 300", "(11)98723-7766"),
("Violeta Varanda", "Av. 9 de Julho, 234", "(16)99988-7766");

INSERT INTO VETERINARIO (NOM_VETER, DES_ESPEC_VETER)
VALUES
("Bartolomeu Ramos", "Geral"),
("Pedro Telles", "Geral"),
("Renata Avelar", "Ortopedia"),
("Marco Vila", "Nutrição");

INSERT INTO ANIMAL (COD_PROP, COD_VETER, NOM_ANIMAL, DAT_NASC_ANIMAL, DES_RACA_ANIMAL, DES_SEXO_ANIMAL)
VALUES
(3, 1, "Lulu", "2011-10-10", "Poodle", "F"),
(1, 2, "Nina", "2012-12-25", "Collie", "F"),
(2, 1, "Furacão", "2013-01-23", "Pit Bull", "M"),
(5, 1, "Ploc", "2014-04-30", "Fox", "M"),
(4, 3, "Golias", "2010-09-27", "Pastor Alemão", "M");

SELECT * FROM VETERINARIO
WHERE DES_ESPEC_VETER = "Geral";

SELECT NOM_ANIMAL, DAT_NASC_ANIMAL, DES_RACA_ANIMAL FROM ANIMAL
WHERE DES_SEXO_ANIMAL = "M";

RENAME TABLE ANIMAL TO ANIMAL_PROPRIETARIO;

ALTER TABLE VETERINARIO
ADD COLUMN DAT_CAD_VETER DATETIME;

UPDATE VETERINARIO
SET DES_ESPEC_VETER = "Ortopedia"
WHERE NOM_VETER = "Bartolomeu Ramos";